---
title: Styx Technology Group
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: consulting@styxtechgroup.com
description: ''
baseurl: ''
url: http://styxtechgroup.com
twitter_username: styxtechgroup
github_username: styxtechgroup
linkedin_link: https://www.linkedin.com/company/styx-technology-group
markdown: kramdown
plugins:
- jekyll-sitemap
